development:
  adapter: postgresql
  encoding: unicode
  database: dylome_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: dylome_test
  host: localhost
  pool: 5
  timeout: 5000
