development:
  :storage: filesystem

test:
  :storage: filesystem

production:
  :storage: s3
  :bucket: <%= ENV['S3_BUCKET'] %>
  :path: ':class/:id/:attachment/:style/:filename'
  :s3_protocol: 'https'
  :s3_credentials:
    aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
